#!/bin/bash -e

#
#    Copyright (c) 2019-2020 Google LLC.
#    Copyright (c) 2016-2018 Nest Labs, Inc.
#    All rights reserved.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#

##
#    @file
#      This file effects a unit test driver utilizing the Python
#      unittest module for the Weave Data Language (WDL) Compiler
#      (WDLC) backend.
#

OS=$(uname -s)

if [ "$OS" == 'Darwin' ]; then
    TOOLS_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
else
    TOOLS_DIR=$(dirname $(readlink -f "$0"))
fi

SCRIPT_DIR=$(python -c "import os,sys; print(os.path.dirname(os.path.realpath(sys.argv[1])))" "$0")

source $SCRIPT_DIR/setup.sh

PYTHONPATH=$SCRIPT_DIR/lib/:$PYTHONPATH python -m unittest discover $TOOLS_DIR/lib "$@"
